png("plot4.png" ,height=480)
par(mfrow = c(2, 2), mar = c(4, 4, 2, 1), oma = c(0, 0, 2, 0))
plot(tfile$tmps,tfile$Global_active_power,type="l",xlab="", ylab="Global Active Power")
plot(tfile$tmps,tfile$Voltage,type="l",xlab="", ylab="Voltage")
plot(tfile$tmps,tfile$Sub_metering_1,type="l",xlab="", ylab="Energy sub metering")
points(tfile$tmps,tfile$Sub_metering_2,type="l",col="red")
points(tfile$tmps,tfile$Sub_metering_3,type="l",col="blue")
legend("topright", pch = "-", col = c("black","blue","red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(tfile$tmps,tfile$Global_reactive_power,type="l",xlab="", ylab="Global reacting power")
dev.off()
